### ISSUE TITLE
Hi ,download  link for the package?

### ISSUE THREAD

**Issue by newmight2015** [H4rmonic/Kadena-Mining-Stratum#1]
git@github.com/moofone/kadena-stratum-pool.git
git@github.com:moofone/ice-nomp-multialgo.git

**Comment by H4rmonic** [comment]
Just updated repo with the node_modules folder which has all of the missing packages. thanks for reporting

**Comment by oliverw** [comment]
> Just updated repo with the node_modules folder which has all of the missing packages. thanks for reporting

You sure `node_modues` contains the deps mentioned by OP? I don't see them.

**Comment by oliverw** [comment]
Nevermind. Found it.

**Comment by mxride** [comment]
@oliverw  Having the same issue as you stated. Did you big the solution?

**Comment by lovelydog1977** [comment]
What version does Node.js use
